// 武器リスト
const weaponList = [
    { name: "未選択", grade: 0, baseAtk: 0, ability: "なし" },
    { name: "疾風：颶風連鎖刃", grade: 10, baseAtk: 520, ability: "疾風" },
    { name: "猛突：インペリアルランス", grade: 9, baseAtk: 265, ability: "猛突" },
    { name: "猛突：思い出の管楽器", grade: 7, baseAtk: 120, ability: "猛突" },
    { name: "猛突：芽吹きのハープ", grade: 5, baseAtk: 60, ability: "猛突" },
    { name: "猛突：気合いの鉢巻", grade: 4, baseAtk: 30, ability: "猛突" },
    { name: "突風：精霊の弓矢", grade: 9, baseAtk: 240, ability: "突風" },
    { name: "突風：鴉扇", grade: 8, baseAtk: 170, ability: "突風" },
    { name: "突風：桜吹雪", grade: 7, baseAtk: 150, ability: "突風" },
    { name: "突風：ウインドスピアー", grade: 6, baseAtk: 100, ability: "突風" },
    { name: "凍結：アイスダガー", grade: 6, baseAtk: 120, ability: "凍結" },
    { name: "凍結：アイスサイズ", grade: 5, baseAtk: 90, ability: "凍結" },
    { name: "凍結：アイスボウ", grade: 3, baseAtk: 50, ability: "凍結" },
    { name: "凍結：義理チョコ", grade: 3, baseAtk: 20, ability: "凍結" },
    { name: "紅舞：ブラッディローズ", grade: 10, baseAtk: 780, ability: "紅舞" },
    { name: "紅舞：衝天ノ神楽鉾", grade: 9, baseAtk: 250, ability: "紅舞" },
    { name: "紅舞：丹青の打楽器", grade: 3, baseAtk: 5, ability: "紅舞" },
    { name: "高揚：エンドオブルイン", grade: 9, baseAtk: 240, ability: "高揚" },
    { name: "高揚：斬魔刀", grade: 8, baseAtk: 200, ability: "高揚" },
    { name: "高揚：金剛双刃", grade: 8, baseAtk: 200, ability: "高揚" },
    { name: "高揚：リリジェンアーク", grade: 7, baseAtk: 190, ability: "高揚" },
    { name: "高揚：脈打つ打楽器", grade: 7, baseAtk: 120, ability: "高揚" },
    { name: "高揚：銀狐の絵筆", grade: 5, baseAtk: 10, ability: "高揚" },
    { name: "盟旗：天響の尖槍", grade: 7, baseAtk: 120, ability: "盟旗" },
    { name: "盟旗：虎将の軍配", grade: 5, baseAtk: 100, ability: "盟旗" },
    { name: "不乱：天巴之御佩刀", grade: 9, baseAtk: 310, ability: "不乱" },
    { name: "不乱：仁双応", grade: 9, baseAtk: 220, ability: "不乱" },
    { name: "不乱：金狐の絵筆", grade: 5, baseAtk: 10, ability: "不乱" },
    { name: "壮健：朧蒼月", grade: 10, baseAtk: 500, ability: "壮健" },
    { name: "壮健：轟天の大槍", grade:9 , baseAtk: 200, ability: "壮健" },
    { name: "大撃：レーヴァテイン『戒』", grade: 9, baseAtk: 240, ability: "大撃" },
    { name: "大撃：エヴィルサイズ", grade: 8, baseAtk: 190, ability: "大撃" },
    { name: "大撃：デス・サイズ", grade: 7, baseAtk: 130, ability: "大撃" },
    { name: "大撃：懐旧の記録盤", grade: 7, baseAtk: 120, ability: "大撃" },
    { name: "大撃：ゴールドソード", grade: 7, baseAtk: 1, ability: "大撃" },
    { name: "大撃：蒼狐の絵筆", grade: 5, baseAtk: 10, ability: "大撃" },
    { name: "五月雨：都牟刈大刀", grade: 7, baseAtk: 160, ability: "五月雨" },
    { name: "五月雨：壮烈な管楽器", grade: 7, baseAtk: 120, ability: "五月雨" },
    { name: "五月雨：金のレイピア", grade: 6, baseAtk: 95, ability: "五月雨" },
    { name: "五月雨：レイピア", grade: 4, baseAtk: 65, ability: "五月雨" },
    { name: "五月雨：三色団子", grade: 4, baseAtk: 50, ability: "五月雨" },
    { name: "強打：荒ぶるターキー", grade: 7, baseAtk: 160, ability: "強打" },
    { name: "強打：ソウルイーター", grade: 6, baseAtk: 120, ability: "強打" },
    { name: "強打：げんこつ斧", grade: 2, baseAtk:35 , ability: "強打" },
    { name: "粉砕：ギガントマキア", grade: 10, baseAtk: 450, ability: "粉砕" },
    { name: "粉砕：アルマース", grade: 9, baseAtk: 210, ability: "粉砕" },
    { name: "粉砕：コランダム", grade: 7, baseAtk: 160, ability: "粉砕" },
    { name: "粉砕：一升瓶", grade: 5, baseAtk: 50, ability: "粉砕" },
    { name: "粉砕：砕けた西瓜", grade: 5, baseAtk: 50, ability: "粉砕" },
    { name: "粉砕：大根", grade: 5, baseAtk:45 , ability: "粉砕" },
    { name: "一斉：布都御魂", grade: 9, baseAtk: 210, ability: "一斉" },
    { name: "一斉：火ノ迦具土", grade: 8, baseAtk: 160, ability: "一斉" },
    { name: "一斉：旋律の弦楽器", grade: 7, baseAtk: 120, ability: "一斉" },
    { name: "一斉：日本刀", grade: 5, baseAtk: 80, ability: "一斉" },
    { name: "一斉：ハリセン", grade: 5, baseAtk: 5, ability: "一斉" },
    { name: "一斉：飛苦無", grade: 4, baseAtk: 45, ability: "一斉" },
    { name: "破茶：ニャンダフルワンド", grade: 5, baseAtk: 10, ability: "破茶" },
    { name: "天晴：照吉丸", grade: 10, baseAtk: 80, ability: "天晴" },
    { name: "福音：天啓の聖鐘", grade: 10, baseAtk: 120, ability: "福音" },
    { name: "福音：交信石", grade: 5, baseAtk: 25, ability: "福音" },
    { name: "爽活：プリマステラ", grade: 10, baseAtk: 120, ability: "爽活" },
    { name: "爽活：フルールロッド", grade: 7, baseAtk: 120, ability: "爽活" },
    { name: "癒唄：バルゴの祝福", grade: 8, baseAtk: 175, ability: "癒唄" },
    { name: "癒唄：マジックスタッフ", grade: 5, baseAtk: 70, ability: "癒唄" },
    { name: "癒唄：極盛チョコクレープ", grade: 4, baseAtk: 125, ability: "癒唄" },
    { name: "回復：魔法使いの杖", grade: 3, baseAtk: 40, ability: "回復" },
    { name: "和属：アストラルスフィア", grade: 10, baseAtk: 650, ability: "和属" },
    { name: "和属：陸志の結扇", grade: 9, baseAtk: 180, ability: "和属" },
    { name: "和属：エルテの宝杖", grade: 6, baseAtk: 110, ability: "和属" },
    { name: "獣属：獅子砕牙", grade: 8, baseAtk: 185, ability: "獣属" },
    { name: "獣属：猛獅子の証", grade: 5, baseAtk: 85, ability: "獣属" },
    { name: "獣属：レッドジェミニ", grade: 5, baseAtk: 50, ability: "獣属" },
    { name: "獣属：ねこパンチ", grade: 4, baseAtk: 80, ability: "獣属" },
    { name: "魔属：ケリュケイオン", grade: 8, baseAtk: 185, ability: "魔属" },
    { name: "魔属：フラジェルム", grade: 4, baseAtk: 85, ability: "魔属" },
    { name: "魔属：小悪魔ナイフ", grade: 4, baseAtk: 80, ability: "魔属" },
    { name: "霊属：レーヴァテイン", grade: 8, baseAtk: 220, ability: "霊属" },
    { name: "霊属：魅惑の肉球", grade: 5, baseAtk: 50, ability: "霊属" },
    { name: "霊属：猛獣用ムチ", grade: 4, baseAtk: 80, ability: "霊属" },
    { name: "無属：弓生矢", grade: 9, baseAtk: 190, ability: "無属" },
    { name: "無属：ティンクルロッド", grade: 4, baseAtk: 80, ability: "無属" },
    { name: "地属：バルムンク", grade: 9, baseAtk: 190, ability: "地属" },
    { name: "地属：大地の鉤爪", grade: 5, baseAtk: 50, ability: "地属" },
    { name: "地属：妖刀『龍殺し』", grade: 4, baseAtk: 80, ability: "地属" },
    { name: "龍属：竜族の紋章", grade: 8, baseAtk: 185, ability: "龍属" },
    { name: "龍属：ドラゴンファング", grade: 5, baseAtk: 85, ability: "龍属" },
    { name: "龍属：ドラゴンクロー", grade: 4, baseAtk: 80, ability: "龍属" },
    { name: "なし：エクスカリバー", grade: 7, baseAtk: 160, ability: "なし" },
    { name: "なし：グレイトソード", grade: 6, baseAtk: 120, ability: "なし" },
    { name: "なし：メガアックス", grade: 5, baseAtk: 90, ability: "なし" },
    { name: "なし：手提げ提灯", grade: 5, baseAtk: 50, ability: "なし" },
    { name: "なし：導きのベル", grade: 5, baseAtk: 30, ability: "なし" },
    { name: "なし：破魔矢", grade: 4, baseAtk: 90, ability: "なし" },
    { name: "なし：かまいたち", grade: 4, baseAtk: 75, ability: "なし" },
    { name: "なし：重い槍", grade: 4, baseAtk: 65, ability: "なし" },
    { name: "なし：カチンコ", grade: 4, baseAtk: 50, ability: "なし" },
    { name: "なし：ギャラルホルン", grade: 4, baseAtk: 50, ability: "なし" },
    { name: "なし：木枝の釣竿", grade: 4, baseAtk: 45, ability: "なし" },
    { name: "なし：兎印の杵", grade: 4, baseAtk: 45, ability: "なし" },
    { name: "なし：カタログ", grade: 4, baseAtk: 45, ability: "なし" },
    { name: "なし：背負い籠", grade: 4, baseAtk: 40, ability: "なし" },
    { name: "なし：豆鉄砲", grade: 4, baseAtk: 30, ability: "なし" },
    { name: "なし：コンパス", grade: 4, baseAtk: 30, ability: "なし" },
    { name: "なし：招待ハガキ", grade: 4, baseAtk: 20, ability: "なし" },
    { name: "なし：バトン", grade: 4, baseAtk: 20, ability: "なし" },
    { name: "なし：隠れ郷への招待状", grade: 4, baseAtk: 15, ability: "なし" },
    { name: "なし：勇者の剣", grade: 3, baseAtk: 60, ability: "なし" },
    { name: "なし：ナイフグローブ", grade: 3, baseAtk: 45, ability: "なし" },
    { name: "なし：灯篭", grade: 3, baseAtk: 40, ability: "なし" },
    { name: "なし：芽切鋏", grade: 3, baseAtk: 40, ability: "なし" },
    { name: "なし：黒き書物", grade: 3, baseAtk: 40, ability: "なし" },
    { name: "なし：イベント出店証", grade: 3, baseAtk: 35, ability: "なし" },
    { name: "なし：スプーン", grade: 3, baseAtk: 30, ability: "なし" },
    { name: "なし：樽のコルク抜き", grade: 3, baseAtk: 30, ability: "なし" },
    { name: "なし：白の手形", grade: 3, baseAtk: 30, ability: "なし" },
    { name: "なし：黒の手形", grade: 3, baseAtk: 30, ability: "なし" },
    { name: "なし：ロックボウ", grade: 2, baseAtk: 30, ability: "なし" },
    { name: "なし：過ちの杖", grade: 2, baseAtk: 30, ability: "なし" },
    { name: "なし：つるはし", grade: 2, baseAtk: 25, ability: "なし" },
    { name: "なし：カラフル熊手", grade: 2, baseAtk: 25, ability: "なし" },
    { name: "なし：エンゲージリング", grade: 2, baseAtk: 22, ability: "なし" },
    { name: "なし：果物ナイフ", grade: 2, baseAtk: 20, ability: "なし" },
    { name: "なし：ランタン", grade: 1, baseAtk: 20, ability: "なし" },
    { name: "なし：アイスピック", grade: 1, baseAtk: 15, ability: "なし" },
    { name: "なし：鉄製の弓", grade: 1, baseAtk: 10, ability: "なし" },
    { name: "なし：観覧のお供", grade: 1, baseAtk: 10, ability: "なし" },
    { name: "なし：木の棒", grade: 1, baseAtk: 5, ability: "なし" }
];

// 防具リスト
const armorList = [
    { name: "未選択", grade: 0, baseDef: 0, ability: "なし" },
    { name: "猛皇：蚩尤ノ冥煌鎧", grade: 10, baseDef: 245, ability: "猛皇" },
    { name: "猛将：飛翔の武冠", grade: 9, baseDef: 35, ability: "猛将" },
    { name: "修羅：鏖魔瞳", grade: 10, baseDef: 500, ability: "修羅" },
    { name: "虎咆：虎乗の覇気", grade: 6, baseDef: 10, ability: "虎咆" },
    { name: "闘争：ネメアーの獅子冠", grade: 9, baseDef: 40, ability: "闘争" },
    { name: "闘争：豪傑な下駄", grade: 7, baseDef: 15, ability: "闘争" },
    { name: "闘争：赤白帽", grade: 7, baseDef: 5, ability: "闘争" },
    { name: "覇王：青藍の巫女服", grade: 9, baseDef: 240, ability: "覇王" },
    { name: "覇王：邪封じの眼帯", grade: 6, baseDef: 40, ability: "覇王" },
    { name: "覇王：戦覇の勲章", grade: 5, baseDef: 10, ability: "覇王" },
    { name: "天佑：竜騎の兜", grade: 9, baseDef: 250, ability: "天佑" },
    { name: "天佑：神楽鈴", grade: 7, baseDef: 130, ability: "天佑" },
    { name: "加護：風雅鳥帽子", grade: 7, baseDef: 120, ability: "加護" },
    { name: "威風：天導の司教冠", grade: 10, baseDef: 230, ability: "威風" },
    { name: "慈恵：フェアリアルヒール", grade: 10, baseDef: 230, ability: "慈恵" },
    { name: "戦略：オブリビオン", grade: 8, baseDef: 180, ability: "戦略" },
    { name: "戦略：エントレンジ", grade: 5, baseDef: 70, ability: "戦略" },
    { name: "遊戯：硝子の靴", grade: 8, baseDef: 35185, ability: "遊戯" },
    { name: "遊戯：氷滑の履物", grade: 5, baseDef: 70, ability: "遊戯" },
    { name: "賢皇：綺羅羊の頭巾", grade: 10, baseDef: 460, ability: "賢皇" },
    { name: "賢将：創世の護翼", grade: 9, baseDef: 310, ability: "賢将" },
    { name: "護鶴：鶴乗の練気", grade: 6, baseDef: 290, ability: "護鶴" },
    { name: "防衛：不滅の炎翼", grade: 9, baseDef: 220, ability: "防衛" },
    { name: "防衛：蒼竜の翼", grade: 7, baseDef: 40, ability: "防衛" },                  
    { name: "鉄壁：零型YOROI『極』", grade: 8, baseDef: 180, ability: "鉄壁" },
    { name: "鉄壁：山神の面", grade: 8, baseDef: 160, ability: "鉄壁" },
    { name: "改命：プロジェクトѰ", grade: 10, baseDef: 230, ability: "改命" },
    { name: "瞑想：プロジェクトΩ", grade: 8, baseDef: 180, ability: "瞑想" },
    { name: "瞑想：プロジェクトΛ", grade: 6, baseDef: 110, ability: "瞑想" },
    { name: "砕身："瞋恚ノ鬼面, grade: 9, baseDef: 35, ability: "砕身" },
    { name: "悪戯：マッドハット", grade: 9, baseDef: 220, ability: "悪戯" },
    { name: "悪戯：オブマスカレード", grade: 7, baseDef: 120, ability: "悪戯" },
    { name: "悪戯：妖狐の尾", grade: 4, baseDef: 80, ability: "悪戯" },
    { name: "勇将：月輪麗明", grade: 9, baseDef: 500, ability: "勇将" },
    { name: "勇将：日輪光明", grade: 9, baseDef: 230, ability: "勇将" },
    { name: "生存：万斛の響鼓", grade: 9, baseDef: 35, ability: "生存" }
];

// 武器アビリティリスト
const weaponAbilityList = [
    { name: "未選択" },
    { name: "疾風" },
    { name: "猛突" },
    { name: "突風" },
    { name: "凍結" },
    { name: "紅舞" },
    { name: "高揚" },
    { name: "盟旗" },
    { name: "不乱" },
    { name: "壮健" },
    { name: "大撃" },
    { name: "五月雨" },
    { name: "強打" },
    { name: "粉砕" },
    { name: "一斉" },
    { name: "破茶" },
    { name: "天晴" },
    { name: "福音" },
    { name: "爽活" },
    { name: "癒唄" },
    { name: "回復" },
    { name: "和属" },
    { name: "獣属" },
    { name: "魔属" },
    { name: "霊属" },
    { name: "無属" },
    { name: "地属" },
    { name: "龍属" },
    { name: "なし" }
];

// 防具アビリティリスト
const armorAbilityList = [
    { name: "未選択" },
    { name: "威風" },
    { name: "虎咆" }
];
