// 武器リスト
const weaponList = [
    { name: "未選択", grade: 0, baseAtk: 0, ability: "なし" },
    { name: "疾風：颶風連鎖刃", grade: 10, baseAtk: 520, ability: "疾風" },
    { name: "猛突：インペリアルランス", grade: 9, baseAtk: 265, ability: "猛突" },
    { name: "猛突：思い出の管楽器", grade: 7, baseAtk: 120, ability: "猛突" },
    { name: "猛突：芽吹きのハープ", grade: 5, baseAtk: 60, ability: "猛突" },
    { name: "猛突：気合いの鉢巻", grade: 4, baseAtk: 30, ability: "猛突" },
    { name: "突風：精霊の弓矢", grade: 9, baseAtk: 240, ability: "突風" },
    { name: "突風：鴉扇", grade: 8, baseAtk: 170, ability: "突風" },
    { name: "突風：桜吹雪", grade: 7, baseAtk: 150, ability: "突風" },
    { name: "突風：ウインドスピアー", grade: 6, baseAtk: 100, ability: "突風" },
    { name: "凍結：アイスダガー", grade: 6, baseAtk: 120, ability: "凍結" },
    { name: "凍結：アイスサイズ", grade: 5, baseAtk: 90, ability: "凍結" },
    { name: "凍結：アイスボウ", grade: 3, baseAtk: 50, ability: "凍結" },
    { name: "凍結：義理チョコ", grade: 3, baseAtk: 20, ability: "凍結" },
    { name: "紅舞：ブラッディローズ", grade: 10, baseAtk: 780, ability: "紅舞" },
    { name: "紅舞：衝天ノ神楽鉾", grade: 9, baseAtk: 250, ability: "紅舞" },
    { name: "紅舞：丹青の打楽器", grade: 3, baseAtk: 5, ability: "紅舞" },
    { name: "高揚：エンドオブルイン", grade: 9, baseAtk: 240, ability: "高揚" },
    { name: "高揚：斬魔刀", grade: 8, baseAtk: 200, ability: "高揚" },
    { name: "高揚：金剛双刃", grade: 8, baseAtk: 200, ability: "高揚" },
    { name: "高揚：リリジェンアーク", grade: 7, baseAtk: 190, ability: "高揚" },
    { name: "高揚：脈打つ打楽器", grade: 7, baseAtk: 120, ability: "高揚" },
    { name: "高揚：銀狐の絵筆", grade: 5, baseAtk: 10, ability: "高揚" },
    { name: "盟旗：天響の尖槍", grade: 7, baseAtk: 120, ability: "盟旗" },
    { name: "盟旗：虎将の軍配", grade: 5, baseAtk: 100, ability: "盟旗" },
    { name: "不乱：天巴之御佩刀", grade: 9, baseAtk: 310, ability: "不乱" },
    { name: "不乱：仁双応", grade: 9, baseAtk: 220, ability: "不乱" },
    { name: "不乱：金狐の絵筆", grade: 5, baseAtk: 10, ability: "不乱" },
    { name: "壮健：朧蒼月", grade: 10, baseAtk: 500, ability: "壮健" },
    { name: "壮健：轟天の大槍", grade:9 , baseAtk: 200, ability: "壮健" },
    { name: "大撃：レーヴァテイン『戒』", grade: 9, baseAtk: 240, ability: "大撃" },
    { name: "大撃：エヴィルサイズ", grade: 8, baseAtk: 190, ability: "大撃" },
    { name: "大撃：デス・サイズ", grade: 7, baseAtk: 130, ability: "大撃" },
    { name: "大撃：懐旧の記録盤", grade: 7, baseAtk: 120, ability: "大撃" },
    { name: "大撃：ゴールドソード", grade: 7, baseAtk: 1, ability: "大撃" },
    { name: "大撃：蒼狐の絵筆", grade: 5, baseAtk: 10, ability: "大撃" },
    { name: "五月雨：都牟刈大刀", grade: 7, baseAtk: 160, ability: "五月雨" },
    { name: "五月雨：壮烈な管楽器", grade: 7, baseAtk: 120, ability: "五月雨" },
    { name: "五月雨：金のレイピア", grade: 6, baseAtk: 95, ability: "五月雨" },
    { name: "五月雨：レイピア", grade: 4, baseAtk: 65, ability: "五月雨" },
    { name: "五月雨：三色団子", grade: 4, baseAtk: 50, ability: "五月雨" },
    { name: "強打：荒ぶるターキー", grade: 7, baseAtk: 160, ability: "強打" },
    { name: "強打：ソウルイーター", grade: 6, baseAtk: 120, ability: "強打" },
    { name: "強打：げんこつ斧", grade: 2, baseAtk:35 , ability: "強打" },
    { name: "粉砕：ギガントマキア", grade: 10, baseAtk: 450, ability: "粉砕" },
    { name: "粉砕：アルマース", grade: 9, baseAtk: 210, ability: "粉砕" },
    { name: "粉砕：コランダム", grade: 7, baseAtk: 160, ability: "粉砕" },
    { name: "粉砕：一升瓶", grade: 5, baseAtk: 50, ability: "粉砕" },
    { name: "粉砕：砕けた西瓜", grade: 5, baseAtk: 50, ability: "粉砕" },
    { name: "粉砕：大根", grade: 5, baseAtk:45 , ability: "粉砕" },
    { name: "一斉：布都御魂", grade: 9, baseAtk: 210, ability: "一斉" },
    { name: "一斉：火ノ迦具土", grade: 8, baseAtk: 160, ability: "一斉" },
    { name: "一斉：旋律の弦楽器", grade: 7, baseAtk: 120, ability: "一斉" },
    { name: "一斉：日本刀", grade: 5, baseAtk: 80, ability: "一斉" },
    { name: "一斉：ハリセン", grade: 5, baseAtk: 5, ability: "一斉" },
    { name: "一斉：飛苦無", grade: 4, baseAtk: 45, ability: "一斉" },
    { name: "破茶：ニャンダフルワンド", grade: 5, baseAtk: 10, ability: "破茶" },
    { name: "天晴：照吉丸", grade: 10, baseAtk: 80, ability: "天晴" },
    { name: "福音：天啓の聖鐘", grade: 10, baseAtk: 120, ability: "福音" },
    { name: "福音：交信石", grade: 5, baseAtk: 25, ability: "福音" },
    { name: "爽活：プリマステラ", grade: 10, baseAtk: 120, ability: "爽活" },
    { name: "爽活：フルールロッド", grade: 7, baseAtk: 120, ability: "爽活" },
    { name: "癒唄：バルゴの祝福", grade: 8, baseAtk: 175, ability: "癒唄" },
    { name: "癒唄：マジックスタッフ", grade: 5, baseAtk: 70, ability: "癒唄" },
    { name: "癒唄：極盛チョコクレープ", grade: 4, baseAtk: 125, ability: "癒唄" },
    { name: "回復：魔法使いの杖", grade: 3, baseAtk: 40, ability: "回復" },
    { name: "和属：アストラルスフィア", grade: 10, baseAtk: 650, ability: "和属" },
    { name: "和属：陸志の結扇", grade: 9, baseAtk: 180, ability: "和属" },
    { name: "和属：エルテの宝杖", grade: 6, baseAtk: 110, ability: "和属" },
    { name: "獣属：獅子砕牙", grade: 8, baseAtk: 185, ability: "獣属" },
    { name: "獣属：猛獅子の証", grade: 5, baseAtk: 85, ability: "獣属" },
    { name: "獣属：レッドジェミニ", grade: 5, baseAtk: 50, ability: "獣属" },
    { name: "獣属：ねこパンチ", grade: 4, baseAtk: 80, ability: "獣属" },
    { name: "魔属：ケリュケイオン", grade: 8, baseAtk: 185, ability: "魔属" },
    { name: "魔属：フラジェルム", grade: 4, baseAtk: 85, ability: "魔属" },
    { name: "魔属：小悪魔ナイフ", grade: 4, baseAtk: 80, ability: "魔属" },
    { name: "霊属：レーヴァテイン", grade: 8, baseAtk: 220, ability: "霊属" },
    { name: "霊属：魅惑の肉球", grade: 5, baseAtk: 50, ability: "霊属" },
    { name: "霊属：猛獣用ムチ", grade: 4, baseAtk: 80, ability: "霊属" },
    { name: "無属：弓生矢", grade: 9, baseAtk: 190, ability: "無属" },
    { name: "無属：ティンクルロッド", grade: 4, baseAtk: 80, ability: "無属" },
    { name: "地属：バルムンク", grade: 9, baseAtk: 190, ability: "地属" },
    { name: "地属：大地の鉤爪", grade: 5, baseAtk: 50, ability: "地属" },
    { name: "地属：妖刀『龍殺し』", grade: 4, baseAtk: 80, ability: "地属" },
    { name: "龍属：竜族の紋章", grade: 8, baseAtk: 185, ability: "龍属" },
    { name: "龍属：ドラゴンファング", grade: 5, baseAtk: 85, ability: "龍属" },
    { name: "龍属：ドラゴンクロー", grade: 4, baseAtk: 80, ability: "龍属" }
];

// 防具リスト
const armorList = [
    { name: "未選択", grade: 0, baseDef: 0, ability: "なし" },
    { name: "猛皇：蚩尤ノ冥煌鎧", grade: 10, baseDef: 245, ability: "猛皇" },
    { name: "猛将：飛翔の武冠", grade: 9, baseDef: 35, ability: "猛将" },
    { name: "修羅：鏖魔瞳", grade: 10, baseDef: 500, ability: "修羅" },
    { name: "虎咆：虎乗の覇気", grade: 6, baseDef: 10, ability: "虎咆" }
];

// 武器アビリティリスト
const weaponAbilityList = [
    { name: "未選択" },
    { name: "疾風" },
    { name: "猛突" },
    { name: "突風" },
    { name: "凍結" },
    { name: "紅舞" },
    { name: "高揚" },
    { name: "盟旗" },
    { name: "不乱" },
    { name: "壮健" },
    { name: "大撃" },
    { name: "五月雨" },
    { name: "強打" },
    { name: "粉砕" },
    { name: "一斉" },
    { name: "破茶" },
    { name: "天晴" },
    { name: "福音" },
    { name: "爽活" },
    { name: "癒唄" },
    { name: "回復" },
    { name: "和属" },
    { name: "獣属" },
    { name: "魔属" },
    { name: "霊属" },
    { name: "無属" },
    { name: "地属" },
    { name: "龍属" }
];

// 防具アビリティリスト
const armorAbilityList = [
    { name: "未選択" },
    { name: "威風" },
    { name: "虎咆" }
];
